### ISSUE TITLE
Add User Data Schema

### ISSUE THREAD

**Issue by logan4473** [logan4473/bakaiti#1]
Add User Data Schema in [models/users.js](https://github.com/logan4473/bakaiti/tree/main/models/users.js) using mongoose with following attributes:

- first name: String
- last name: String
- mobile : Number
- username : String
- Socket Id : String
- hash : String
- salt : String
- contacts : Array of Objects : { username , socket id }

**Comment by suryansh011** [comment]
https://github.com/suryansh011/bakaiti/blob/main/models/users.js

**Comment by suryansh011** [comment]
https://github.com/suryansh011/bakaiti/blob/main/models/users.js

Do we need something different than the above?
What else needs to be added?
